[build]
  command = "npm install && npm run build"
  publish = "src/dist"
  base = "src"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "src/dist"
  autoLaunch = true 