-- 0001_create_auth_core_tables.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.

BEGIN TRANSACTION;

-- Users table (core)
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,                       -- UUID
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    hashed_password TEXT NOT NULL,             -- Argon2id output
    totp_secret_encrypted BLOB,                -- AES-256-GCM encrypted, nullable
    totp_configured BOOLEAN DEFAULT FALSE,
    recovery_codes_hashed JSON,                -- JSON array of hashed one-time codes
    public_pqc_key TEXT NULL,                  -- public key (PQC) for hybrid KEM
    public_sign_key TEXT NULL,                 -- public signing key (optional)
    encrypted_profile_blob BLOB NULL,          -- optional client-side encrypted profile
    account_type TEXT NOT NULL DEFAULT 'free', -- enum: free|premium|enterprise|admin
    account_status TEXT NOT NULL DEFAULT 'pending_verification', -- pending_verification|active|suspended|deleted
    domain TEXT NULL,                          -- user's mailbox domain (nullable until bound)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_domain ON users(username, domain);

-- Recovery codes (one-time codes table) — better than storing array
CREATE TABLE IF NOT EXISTS recovery_codes (
    id TEXT PRIMARY KEY,           -- UUID
    user_id TEXT NOT NULL,
    code_hashed TEXT NOT NULL,     -- hashed one-time code (Argon2id or SHA256+pepper)
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recovery_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_recovery_user ON recovery_codes(user_id);

-- Sessions / refresh tokens (store hashed tokens)
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,           -- UUID
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL,      -- store hash of opaque token (never store raw token)
    device_info TEXT NULL,
    ip_address TEXT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

-- Domains (for paid / enterprise)
CREATE TABLE IF NOT EXISTS domains (
    id TEXT PRIMARY KEY,
    domain_name TEXT NOT NULL UNIQUE,
    owner_user_id TEXT NULL,
    org_id TEXT NULL,
    verified BOOLEAN DEFAULT FALSE,
    dns_verification_token TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_domain_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Mailbox identities (username@domain aliasing)
CREATE TABLE IF NOT EXISTS mailbox_identities (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    domain_id TEXT NOT NULL,
    email_identity TEXT NOT NULL,   -- username@domain
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mailbox_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_mailbox_domain FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mailbox_identity ON mailbox_identities(email_identity);

-- Audit logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT NULL,
    action TEXT NOT NULL,
    resource_type TEXT,
    resource_id TEXT,
    ip_address TEXT,
    user_agent TEXT,
    metadata JSON,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs(timestamp);

COMMIT;
