-- 0002_add_email_verification_fields.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Adds email verification fields to users table

BEGIN TRANSACTION;

-- Add email verification fields to users table
ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN verification_code TEXT NULL; -- hashed verification code
ALTER TABLE users ADD COLUMN verification_code_expires_at TIMESTAMP NULL;

-- Create index for verification code lookups (for performance)
CREATE INDEX IF NOT EXISTS idx_users_verification_code ON users(verification_code);

-- Update existing users to have email_verified = FALSE (they need to verify)
UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL;

COMMIT;
