-- 0003_add_mfa_fields.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Adds MFA/TOTP fields to users table

BEGIN TRANSACTION;

-- Add MFA/TOTP fields to users table
ALTER TABLE users ADD COLUMN totp_secret TEXT NULL; -- encrypted TOTP secret
ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN backup_codes_hashed JSON NULL; -- hashed backup codes array

-- Create index for MFA-enabled users (for performance)
CREATE INDEX IF NOT EXISTS idx_users_mfa_enabled ON users(mfa_enabled);

-- Update existing users to have mfa_enabled = FALSE
UPDATE users SET mfa_enabled = FALSE WHERE mfa_enabled IS NULL;

COMMIT;
