-- 0004_create_subscriptions_table.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Creates subscriptions table for payment and billing management

BEGIN TRANSACTION;

-- Subscriptions table for payment and billing management
CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY,                    -- UUID
    user_id TEXT NOT NULL,                  -- Foreign key to users table
    stripe_customer_id TEXT NULL,           -- Stripe customer ID (encrypted)
    stripe_subscription_id TEXT NULL,       -- Stripe subscription ID (encrypted)
    status TEXT NOT NULL DEFAULT 'inactive', -- active, inactive, canceled, past_due, trialing
    plan TEXT NOT NULL DEFAULT 'free',      -- free, premium, enterprise
    start_date TIMESTAMP NULL,              -- Subscription start date
    end_date TIMESTAMP NULL,                -- Subscription end date
    trial_end_date TIMESTAMP NULL,          -- Trial period end date
    cancel_at_period_end BOOLEAN DEFAULT FALSE, -- Whether to cancel at period end
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan ON subscriptions(plan);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_customer ON subscriptions(stripe_customer_id);

COMMIT;
