-- 0005_create_domains_table.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Creates domains table for custom domain management

BEGIN TRANSACTION;

-- Domains table for custom domain management
CREATE TABLE IF NOT EXISTS domains (
    id TEXT PRIMARY KEY,                    -- UUID
    user_id TEXT NULL,                      -- Foreign key to users table (nullable for org domains)
    organization_id TEXT NULL,              -- Foreign key to organizations table (nullable)
    domain_name TEXT NOT NULL,              -- The custom domain (e.g., example.com)
    verified BOOLEAN DEFAULT FALSE,         -- Whether domain ownership is verified
    verification_code TEXT NULL,            -- DNS verification code (encrypted)
    verification_method TEXT NULL,          -- TXT or CNAME verification method
    dns_record_value TEXT NULL,             -- Expected DNS record value (encrypted)
    verification_attempts INTEGER DEFAULT 0, -- Number of verification attempts
    last_verification_attempt TIMESTAMP NULL, -- Last verification attempt timestamp
    is_primary BOOLEAN DEFAULT FALSE,       -- Whether this is the user's primary domain
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_domain_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_domain_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE UNIQUE INDEX IF NOT EXISTS idx_domains_domain_name ON domains(domain_name);
CREATE INDEX IF NOT EXISTS idx_domains_user ON domains(user_id);
CREATE INDEX IF NOT EXISTS idx_domains_organization ON domains(organization_id);
CREATE INDEX IF NOT EXISTS idx_domains_verified ON domains(verified);
CREATE INDEX IF NOT EXISTS idx_domains_primary ON domains(is_primary);

COMMIT;
