-- 0006_create_organizations_table.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Creates organizations table for enterprise multi-user management

BEGIN TRANSACTION;

-- Organizations table for enterprise multi-user management
CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,                    -- UUID
    name TEXT NOT NULL,                     -- Organization name
    admin_user_id TEXT NOT NULL,            -- Foreign key to users table (admin)
    domain TEXT NULL,                       -- Organization's primary domain
    max_users INTEGER DEFAULT 10,           -- Maximum number of users allowed
    subscription_id TEXT NULL,              -- Foreign key to subscriptions table
    settings JSON NULL,                     -- Organization-specific settings
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_admin FOREIGN KEY (admin_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_org_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL
);

-- Organization members table for user-organization relationships
CREATE TABLE IF NOT EXISTS organization_members (
    id TEXT PRIMARY KEY,                    -- UUID
    organization_id TEXT NOT NULL,          -- Foreign key to organizations table
    user_id TEXT NOT NULL,                  -- Foreign key to users table
    role TEXT NOT NULL DEFAULT 'member',    -- admin, member, viewer
    invited_by TEXT NULL,                   -- User ID who invited this member
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'active',  -- active, pending, suspended
    CONSTRAINT fk_org_member_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_org_member_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_org_member_inviter FOREIGN KEY (invited_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Indexes for performance
CREATE UNIQUE INDEX IF NOT EXISTS idx_org_members_org_user ON organization_members(organization_id, user_id);
CREATE INDEX IF NOT EXISTS idx_org_members_user ON organization_members(user_id);
CREATE INDEX IF NOT EXISTS idx_org_members_role ON organization_members(role);
CREATE INDEX IF NOT EXISTS idx_org_members_status ON organization_members(status);
CREATE INDEX IF NOT EXISTS idx_organizations_admin ON organizations(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_organizations_domain ON organizations(domain);

COMMIT;
