-- 0007_update_users_account_types.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Updates users table to support premium and enterprise account types

BEGIN TRANSACTION;

-- Update account_type to support premium and enterprise
-- Note: SQLite doesn't support ALTER COLUMN, so we'll add a new column and migrate data
ALTER TABLE users ADD COLUMN account_type_new TEXT DEFAULT 'free';

-- Update existing users to use the new account_type column
UPDATE users SET account_type_new = account_type WHERE account_type IS NOT NULL;

-- Add organization_id column for enterprise users
ALTER TABLE users ADD COLUMN organization_id TEXT NULL;

-- Add foreign key constraint for organization_id
-- Note: This will be added after the organizations table is created

-- Add indexes for the new columns
CREATE INDEX IF NOT EXISTS idx_users_account_type_new ON users(account_type_new);
CREATE INDEX IF NOT EXISTS idx_users_organization ON users(organization_id);

-- Update the account_type constraint to allow premium and enterprise
-- Note: In SQLite, we can't modify constraints directly, so the application layer will enforce this

COMMIT;
