-- 0008_create_inbox_tables.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.

BEGIN TRANSACTION;

-- Mailbox folders for organizing emails
CREATE TABLE IF NOT EXISTS mailbox_folders (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    folder_type TEXT NOT NULL DEFAULT 'custom', -- inbox, sent, trash, custom
    parent_folder_id TEXT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_folder_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_folder_parent FOREIGN KEY (parent_folder_id) REFERENCES mailbox_folders(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_folders_user ON mailbox_folders(user_id);
CREATE INDEX IF NOT EXISTS idx_folders_type ON mailbox_folders(user_id, folder_type);

-- Email messages (encrypted content)
CREATE TABLE IF NOT EXISTS email_messages (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    folder_id TEXT NOT NULL,
    message_id TEXT NOT NULL, -- RFC 5322 Message-ID
    thread_id TEXT NULL, -- For conversation threading
    from_address TEXT NOT NULL, -- Encrypted
    to_addresses TEXT NOT NULL, -- Encrypted JSON array
    cc_addresses TEXT NULL, -- Encrypted JSON array
    bcc_addresses TEXT NULL, -- Encrypted JSON array
    subject TEXT NOT NULL, -- Encrypted
    body_encrypted BLOB NOT NULL, -- AES-256-GCM encrypted
    body_type TEXT NOT NULL DEFAULT 'text/plain', -- text/plain, text/html
    attachments_encrypted BLOB NULL, -- Encrypted JSON array of attachment metadata
    headers_encrypted BLOB NULL, -- Encrypted email headers
    size_bytes INTEGER NOT NULL DEFAULT 0,
    is_read BOOLEAN DEFAULT FALSE,
    is_important BOOLEAN DEFAULT FALSE,
    is_starred BOOLEAN DEFAULT FALSE,
    received_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_folder FOREIGN KEY (folder_id) REFERENCES mailbox_folders(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_user ON email_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_folder ON email_messages(folder_id);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON email_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_messages_received ON email_messages(received_at);
CREATE INDEX IF NOT EXISTS idx_messages_unread ON email_messages(user_id, is_read);

-- Email labels/tags for organization
CREATE TABLE IF NOT EXISTS email_labels (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT DEFAULT '#007bff',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_label_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_labels_user ON email_labels(user_id);

-- Many-to-many relationship between messages and labels
CREATE TABLE IF NOT EXISTS message_labels (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL,
    label_id TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ml_message FOREIGN KEY (message_id) REFERENCES email_messages(id) ON DELETE CASCADE,
    CONSTRAINT fk_ml_label FOREIGN KEY (label_id) REFERENCES email_labels(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ml_unique ON message_labels(message_id, label_id);

-- Email drafts
CREATE TABLE IF NOT EXISTS email_drafts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    folder_id TEXT NULL, -- Draft folder
    to_addresses TEXT NULL, -- Encrypted JSON array
    cc_addresses TEXT NULL, -- Encrypted JSON array
    bcc_addresses TEXT NULL, -- Encrypted JSON array
    subject TEXT NULL, -- Encrypted
    body_encrypted BLOB NULL, -- AES-256-GCM encrypted
    body_type TEXT NOT NULL DEFAULT 'text/plain',
    attachments_encrypted BLOB NULL, -- Encrypted JSON array
    is_auto_save BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_draft_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_folder FOREIGN KEY (folder_id) REFERENCES mailbox_folders(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_drafts_user ON email_drafts(user_id);

COMMIT;
