-- 0009_create_analytics_events_table.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.

BEGIN TRANSACTION;

-- Analytics events table for privacy-friendly event logging
CREATE TABLE IF NOT EXISTS analytics_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    user_hash TEXT NOT NULL, -- SHA256 hash of user ID for privacy
    metadata TEXT NULL, -- JSON metadata (no personal data)
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_analytics_event_type ON analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_timestamp ON analytics_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_analytics_user_hash ON analytics_events(user_hash);

COMMIT;
