-- 0010_add_fallback_email_recovery.sql
-- DO NOT EDIT THIS FILE ONCE APPLIED. Create new migrations for changes.
-- Adds mandatory fallback email and recovery key fields to users table

BEGIN TRANSACTION;

-- Add fallback email and recovery key fields to users table
ALTER TABLE users ADD COLUMN fallback_email TEXT NULL;
ALTER TABLE users ADD COLUMN fallback_email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN recovery_private_key_hashed TEXT NULL;

-- Create index for fallback email lookups (for performance)
CREATE INDEX IF NOT EXISTS idx_users_fallback_email ON users(fallback_email);

-- Update existing users to have fallback_email_verified = FALSE (they need to verify)
UPDATE users SET fallback_email_verified = FALSE WHERE fallback_email_verified IS NULL;

COMMIT;
